services:
  backend:
    port: 5000
    image: reploy/go:v1
    commands: 
      - cd backend
      - go build -o reploy
      - ./reploy
  frontend:
    port: 3000
    image: reploy/nodejs:v1
    commands: 
      - cd frontend
      - npm install
      - npm start
  redis:
    port: 6379
    image: reploy/redis:v1
