services:
  react:
    port: 3000
    runtime: reactjs
    path: frontend
    build:
      - yarn install
    serve:
      - yarn start
  redis:
    port: 6379
    runtime: redis
    do-not-expose: true
