cache:
  - file: frontend/yarn.lock
    path: frontend/node_modules
services:
  frontend:
    runtime: reactjs
    port: 3000
    path: frontend
    build:
      - yarn add react-scripts@3.0.1 -g
      - yarn install
      - yarn build
    serve:
      - npx serve build/ -l 3000
  backend:
    port: 5000
    runtime: go
    path: backend
    build: 
      - go build -o reploy
    serve:
      - ./reploy
  redis:
    do-not-expose: true
    port: 6379
    runtime: redis

