build-timeout-seconds: 1200
on:
  branches:
    - staging
setup:
  commands:
    # - mkdir pg_data_dir
    - cd pg_data_dir
    - PGPASSWORD="default" pg_dump -h 35.202.244.19 -U postgres > file.sql
    - tail -f /dev/null
services:
  backend:
    port: 5000
    runtime: go
    build:
      - cd backend
      - go build -o reploy
    serve:
      - ./reploy
  frontend:
    port: 3000
    runtime: reactjs
    build:
      - cd frontend
      - yarn install
      - yarn build
    serve:
      - cd frontend
      - npx serve build/ -l 3000
  redis:
    port: 6379
    runtime: redis
    do-not-expose: true
  postgres:
    port: 5432
    runtime: postgres
    mount-path-container: /docker-entrypoint-initdb.d
    mount-path-volume: pg_data_dir
    do-not-expose: true
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
