services:
  backend:
    port: 5000
    runtime: go
    path: backend
    build: 
      - go build -o reploy
      - exit 1
    serve:
      - ./reploy
  frontend:
    port: 3000
    health: test/
    runtime: reactjs
    path: frontend
    build:
      - exit 1
      - yarn install
      - yarn build
    serve:
      - npx serve build/ -l 3000 -s
  redis:
    port: 6379
    runtime: redis
    do-not-expose: true
  postgres:
    port: 5432
    runtime: postgres
    mount-path-container: /docker-entrypoint-initdb.d
    mount-path-volume: pg_data_dir
    do-not-expose: true
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
