services:
  backend:
    port: 5000
    language: go
    commands: 
      - cd backend
      - go build -o reploy
      - ./reploy
  frontend:
    port: 3000
    language: reactjs
    commands: 
      - cd frontend
      - yarn install
      - yarn build
      - npx serve build/ -l 3000
  redis:
    do-not-expose: true
    port: 6379
    image: reploy/redis:v1
