build-timeout-seconds: 1200
on:
  branches:
    - staging
cache:
  - file: frontend/yarn.lock
    path: frontend/node_modules
services:
  backend:
    port: 5000
    runtime: go
    path: backend
    build: 
      - go build -o reploy
    serve:
      - ./reploy
  frontend:
    port: 3000
    runtime: reactjs
    path: frontend
    build:
      - yarn install
      - sleep 180
      - yarn build
    serve:
      - npx serve build/ -l 3000
  redis:
    port: 6379
    runtime: redis
    do-not-expose: true
  postgres:
    port: 5432
    runtime: postgres
    mount-path-container: /docker-entrypoint-initdb.d
    mount-path-volume: pg_data_dir
    do-not-expose: true
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
