services:
  backend:
    port: 5000
    runtime: go
    build:
      - cd backend
      - go build -o reploy
    serve:
      - ./reploy
  frontend:
    port: 3000
    runtime: reactjs
    path: frontend
    build:
      - yarn install
    serve:
      - yarn start
  redis:
    port: 6379
    runtime: redis
    do-not-expose: true
  postgres:
    port: 5432
    runtime: postgres
    do-not-expose: true
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
