registry-auth:
  - registry: gcr.io
    password-env-var: GCP_KEY
services:
  backend:
    ports:
      - name: smtp
        port: 1025
        do-not-expose: true
      - name: web
        port: 5000
    runtime: go
    path: backend
    build:
      - go build -o reploy
    serve:
      - go build -o reploy
      - ./reploy
  frontend:
    port: 3000
    image: gcr.io/github-api/node13:v1
    path: frontend
    build:
      - yarn install
    serve:
      - yarn start
  redis:
    port: 6379
    runtime: redis
    do-not-expose: true
  postgres:
    port: 5432
    runtime: postgres
    do-not-expose: true
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
