cache:
  - file: frontend/yarn.lock
    path: frontend/.yarn-cache
services:
  frontend:
    image: reploy/node
    port: 3000
    path: frontend
    build:
      - yarn config set cache-folder $(pwd)/.yarn-cache
      - yarn cache dir
      - yarn install --frozen-lockfile
      - yarn build
      - echo "hi"
      - ls -a .yarn-cache
    serve:
      - npx serve build/ -l 3000
    environment:
      SKIP_PREFLIGHT_CHECK: true
