cache:
  - file: frontend/yarn.lock
    path: frontend/node_modules
services:
  frontend:
    image: reploy/node
    port: 3000
    path: frontend
    build:
      - yarn install --frozen-lockfile
      - yarn build
    serve:
      - npx serve build/ -l 3000
    environment:
      SKIP_PREFLIGHT_CHECK: true
  backend:
    port: 5000
    runtime: go
    path: backend
    build: 
      - go build -o reploy
    serve:
      - ./reploy
  redis:
    do-not-expose: true
    port: 6379
    runtime: redis
