build-timeout-seconds: 1200
on:
  branches:
    - staging
services:
  backend:
    port: 5000
    runtime: go
    build:
      - cd backend
      - go build -o reploy
    serve:
      - ./reploy
    environment:
      KEY1: val1
      KEY2: |
        define( 'WP_REDIS_CLIENT', 'predis' );
        define( 'WP_REDIS_SCHEME', 'tcp' );
        define( 'WP_REDIS_HOST', 'redis' );
        define( 'WP_REDIS_PORT', '6379' );
        define( 'WP_REDIS_PASSWORD', 'xxxxxxxxxxxxxxx' );
        define( 'WP_REDIS_DATABASE', '0' );
        define( 'WP_REDIS_MAXTTL', '21600' );
        define( 'WP_CACHE_KEY_SALT', 'xx_ ');
        define( 'WP_REDIS_SELECTIVE_FLUSH', 'xx_ ');
        define( 'WP_AUTO_UPDATE_CORE', false );
  frontend:
    port: 3000
    runtime: reactjs
    build:
      - cd frontend
      - yarn install
      - yarn build
    serve:
      - cd frontend
      - npx serve build/ -l 3000
  redis:
    port: 6379
    runtime: redis
    do-not-expose: true
  postgres:
    port: 5432
    runtime: postgres
    mount-path-container: /docker-entrypoint-initdb.d
    mount-path-volume: pg_data_dir
    do-not-expose: true
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
