services:
  backend:
    port: 5000
    image: reploy/go:v1
    commands: 
      - cd backend
      - printenv
      - env
      - go build -o reploy
      - ./reploy
  frontend:
    port: 3000
    image: reploy/nodejs:v1
    commands: 
      - cd frontend
      - printenv
      - env
      - npm install
      - npm run build
      - npx serve build/ -l 3000
  redis:
    do-not-expose: true
    port: 6379
    image: reploy/redis:v1
