id: rxzklsiwspodh2cnffer7g
services:
  backend:
    port: 5000
    image: reploy/go:v1
    commands:
      - cd backend
      - go run .    
  redis:
    port: 6379
    image: reploy/redis:v1
  frontend:
    port: 3000
    image: reploy/nodejs:v1
    environment:
      CHOKIDAR_USEPOLLING: true
    commands:
      - cd frontend
      - npm install
      - npm start    
