registry-auth:
  - registry: registry.gitlab.com
    username: monofuel34089
    password-env-var: CLOUD_SECRET
services:
  backend:
    port: 25565
    image: registry.gitlab.com/monofuel34089/mineserver/forge